# Generated by Django 6.0.6 on 2026-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentilationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('changed_by', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ventilation Status',
            },
        ),
    ]
